In [41]:
import pandas as pd
import numpy as np

df = pd.read_csv('/Users/bean/Documents/Doctorate/1Research/MapMetadata/mapmetadata/20250721-095144.csv')
# df = pd.read_csv('/Users/bean/Documents/Doctorate/1Research/MapMetadata/mapmetadata/data_partiton_test.csv')

In [42]:
df

traj_id            timestamp  latitude  longitude
0   0_10-0  2021-01-01 07:30:00        30         21
1   0_10-0  2021-01-01 07:31:30        51         91
2   0_10-0  2021-01-01 07:32:00        39         28
3   0_10-0  2021-01-01 07:33:30        93         73
4   0_10-0  2021-01-01 07:34:00         4         46
5   0_10-0  2021-01-01 07:37:30        35         55
6   0_10-0  2021-01-01 07:38:00        70         64
7   0_10-0  2021-01-01 07:38:30        11         27
8   0_10-0  2021-01-01 07:39:00        82         18
9   0_10-0  2021-01-01 07:39:30        40         91
10  0_10-0  2021-01-01 07:40:00        40          0

In [11]:
def get_timestamp_list(col):
    dt = pd.to_datetime(col, errors = 'coerce')
    return dt.to_list()

In [22]:
self_max_time_diff = pd.Timedelta(minutes=2)
k = 2

# DATASET
self_traj_ids = df['traj_id'].to_list()
self_timestamps = get_timestamp_list(col=df['timestamp'])
self_latitudes = df['latitude'].to_list()
self_longitudes = df['longitude'].to_list()

self_num_points = len(df)

# # INDEXES
# time_group_idx = get_time_group_idx()
# space_groups, space_group_idx = get_space_groups()

In [28]:
t_list = []
t_list.append(4)
t_list.append(5)
t_list.append(t_list[-1])
t_list

[4, 5, 5]

In [ ]:
# time_group_intervals = []
# time_intervals_expanded = []
# time_diff = []
# dist_diff = []
# s = 0
# group_time_diff = pd.Timedelta(minutes=0)
# prev_id = self_traj_ids[0]
# prev_lat = self_latitudes[0]
# prev_lon = self_longitudes[0]

# for i in range(1, (self_num_points-1)):

#     cur_id = self_traj_ids[i]
#     cur_lat = self_latitudes[i]
#     cur_lon = self_longitudes[i]
#     cur_timestamp = self_timestamps[i]
    
#     # TODO: make two if statements one if statement case
#     # calculate change in time and distance for every point pair (w/in a trajectory)
#     if cur_id == prev_id:
#         group_time_diff = cur_timestamp - self_timestamps[s]
#         time_diff.append((cur_timestamp - self_timestamps[i - 1]).total_seconds())
#         dist_diff.append(round(np.linalg.norm(np.array([cur_lon, cur_lat], dtype=np.float32) - np.array([prev_lon, prev_lat], dtype=np.float32)), 2))

#     if (group_time_diff > self_max_time_diff) or (cur_id != prev_id):
#         time_group_intervals.append((s, i))
#         time_intervals_expanded.append(np.arange(s, i))
#         s = i
#         prev_id = cur_id

#     prev_lat = cur_lat
#     prev_lon = cur_lon

# # last index - check if ids of last two points are the same, add correct ids to lists
# last_i = self_num_points - 1    # == i + 1
# cur_id = self_traj_ids[last_i]
# if cur_id != prev_id:   # corner case - last point not in same trajectory as penultimate point
#     cur_timestamp = self_timestamps[last_i]
#     group_time_diff = cur_timestamp - self_timestamps[s]

#     # add last group from loop
#     time_group_intervals.append((s, i))
#     time_intervals_expanded.append(np.arange(s, last_i))

#     # add last point
#     time_group_intervals.append(last_i, last_i)
#     time_intervals_expanded.append(np.arange(last_i, self_num_points))
# else:   # standard case - last point in same trajectory as penultimate point
#     time_group_intervals.append((s, last_i))
#     time_intervals_expanded.append(np.arange(s, self_num_points))

# # last index - get time and distance difference
# cur_lat = self_latitudes[last_i]
# cur_lon = self_longitudes[last_i]
# time_diff.append((self_timestamps[last_i] - self_timestamps[i]).total_seconds())
# dist_diff.append(round(np.linalg.norm(np.array([cur_lon, cur_lat], dtype=np.float32) - np.array([prev_lon, prev_lat], dtype=np.float32)), 2))

# indices = [end for _, end in time_group_intervals[:-1]]  #TODO: make this the time_group_idx if we only need these vals   

# dt = [d/t for d, t in zip(dist_diff,time_diff)]
# dt.append(dt[-1])   # last two points have the same value

# # return indices, time_intervals_expanded, dt

In [ ]:
time_group_intervals = []
time_intervals_expanded = []
time_diff = []
dist_diff = []
s = 0
group_time_diff = pd.Timedelta(minutes=0)
prev_id = self_traj_ids[0]
prev_lat = self_latitudes[0]
prev_lon = self_longitudes[0]
prev_timestamp = self_timestamps[0]

for i in range(1, (self_num_points-1)):

    cur_id = self_traj_ids[i]
    cur_lat = self_latitudes[i]
    cur_lon = self_longitudes[i]
    cur_timestamp = self_timestamps[i]

    if cur_id == prev_id:
        time_diff.append((cur_timestamp - prev_timestamp).total_seconds())
        dist_diff.append(round(np.linalg.norm(np.array([cur_lon, cur_lat], dtype=np.float32) - np.array([prev_lon, prev_lat], dtype=np.float32)), 2))

        group_time_diff = cur_timestamp - self_timestamps[s]
        if (group_time_diff > self_max_time_diff):
            time_group_intervals.append((s,i))
            time_intervals_expanded.append(np.arange(s,i))
            s = i
    else:
        # last two points of prev trajectory get same speed
        time_diff.append(time_diff[-1])
        dist_diff.append(dist_diff[-1])
        prev_id = cur_id
    
    prev_lat = cur_lat
    prev_lon = cur_lon
    prev_timestamp = cur_timestamp

# last index - check if ids of last two points are the same, add correct ids to lists
last_i = self_num_points - 1    # == i + 1
cur_id = self_traj_ids[last_i]

if cur_id != prev_id:   # corner case - last point not in same trajectory as penultimate point
    # add last group from loop
    time_group_intervals.append((s, i))
    time_intervals_expanded.append(np.arange(s, last_i))    # need last_i == i + 1 because we want [s, i]
    time_diff.append(time_diff[-1])
    dist_diff.append(dist_diff[-1])

    # add last point
    time_group_intervals.append(last_i, last_i)
    time_intervals_expanded.append(np.arange(last_i, self_num_points))
    time_diff.append(None)
    dist_diff.append(None)

else:   # standard case - last point in same trajectory as penultimate point
    time_group_intervals.append((s, last_i))
    time_intervals_expanded.append(np.arange(s, self_num_points))

    cur_lat = self_latitudes[last_i]
    cur_lon = self_longitudes[last_i]
    time_diff.append((self_timestamps[last_i] - self_timestamps[i]).total_seconds())
    dist_diff.append(round(np.linalg.norm(np.array([cur_lon, cur_lat], dtype=np.float32) - np.array([prev_lon, prev_lat], dtype=np.float32)), 2))

indices = [end for _, end in time_group_intervals[:-1]]  #TODO: make this the time_group_idx if we only need these vals   

dt = [d/t for d, t in zip(dist_diff,time_diff)]
dt.append(dt[-1])   # last two points have the same value

# return indices, time_intervals_expanded, dt

In [26]:
time_intervals_expanded

[array([0, 1, 2, 3, 4, 5, 6]),
 array([ 7,  8,  9, 10, 11, 12, 13]),
 array([14, 15]),
 array([16, 17, 18]),
 array([19, 20, 21]),
 array([22, 23, 24]),
 array([25, 26, 27]),
 array([28, 29, 30]),
 array([31, 32, 33]),
 array([34, 35, 36]),
 array([37, 38, 39]),
 array([40, 41, 42]),
 array([43, 44, 45]),
 array([46, 47]),
 array([48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]),
 array([61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73]),
 array([74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84]),
 array([ 85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
        111, 112, 113]),
 array([114]),
 array([115]),
 array([116]),
 array([117, 118, 119])]

In [36]:
time_group_intervals

[(0, 7),
 (7, 14),
 (14, 17),
 (17, 20),
 (20, 23),
 (23, 26),
 (26, 29),
 (29, 32),
 (32, 35),
 (35, 38),
 (38, 41),
 (41, 44),
 (44, 47),
 (47, 49),
 (49, 62),
 (62, 75),
 (75, 86),
 (86, 115),
 (115, 116),
 (116, 117),
 (117, 119)]

In [38]:
grouped_lats = np.matrix([[l[0], l[-1]] for l in np.split(self_latitudes, indices)])
grouped_lons = np.matrix([[l[0], l[-1]] for l in np.split(self_longitudes, indices)])

sorted_lats = np.asarray(np.sort(grouped_lats, axis=1))
sorted_lons = np.asarray(np.sort(grouped_lons, axis=1))

In [39]:
indices

[7,
 14,
 17,
 20,
 23,
 26,
 29,
 32,
 35,
 38,
 41,
 44,
 47,
 49,
 62,
 75,
 86,
 115,
 116,
 117]

In [46]:
def get_bbox(lat, lon, labels, i):
    """
    Return [min_long, min_lat, max_long, max_lat] == [left, bottom, right, top]
    """
    g_lat = np.matrix([row for row, l in zip(lat, labels) if l == i])
    g_lon = np.matrix([row for row, l in zip(lon, labels) if l == i])

    return [np.min(g_lon), np.min(g_lat), np.max(g_lon), np.max(g_lat)]


In [40]:
from sklearn.cluster import KMeans
# sorted_lats, sorted_lons = get_extrema()
mbrs = np.hstack([sorted_lats, sorted_lons])

centroids = [( (x1+x2)/2, (y1+y2)/2 ) for y1, y2, x1, x2 in mbrs]
kmeans = KMeans(n_clusters = k).fit(centroids)
labels = kmeans.labels_

space_groups = []
for i in range(k):
    space_groups.append(get_bbox(lat=sorted_lats, lon=sorted_lons, labels=labels, i=i))

NameError: name 'get_bbox' is not defined

In [47]:
new_df = np.stack([longitudes, latitudes]).transpose()
points_in_time_groups = np.split(new_df, indices)
points_in_space_groups = [row for row, l in zip(points_in_time_groups, labels) if l == 0]

In [112]:


# Step 3: Select only the groups you're interested in (e.g., label == 0)
selected_rows = []
selected_idx = []

for split, idx, label in zip(points_in_time_groups, time_group_idx, labels):
    # if label == 0:
    selected_rows.append(split)
    selected_idx.append(idx)

print("selected rows")
print(selected_rows)
print("\nselected index")
print(selected_idx)

# Step 4: Combine them
combined_rows = np.vstack(selected_rows)
combined_indices = np.concatenate(selected_idx)

print("\ncombined rows")
print(combined_rows)
print("combined indices")
print(combined_indices)

# Step 5: Sort back to original order
sorted_order = np.argsort(combined_indices)
restored_array = combined_rows[sorted_order]

print("\nsorted order")
print(sorted_order)
print("\nrestored array")
print(restored_array)


selected rows
[array([[21, 30],
       [91, 51],
       [28, 39]]), array([[73, 93],
       [46,  4]]), array([[55, 35],
       [64, 70],
       [27, 11],
       [18, 82],
       [91, 40],
       [ 0, 40]])]

selected index
[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8, 9])]

combined rows
[[21 30]
 [91 51]
 [28 39]
 [73 93]
 [46  4]
 [55 35]
 [64 70]
 [27 11]
 [18 82]
 [91 40]
 [ 0 40]]
combined indices
[0 1 2 3 4 5 6 7 8 9]

sorted order
[0 1 2 3 4 5 6 7 8 9]

restored array
[[21 30]
 [91 51]
 [28 39]
 [73 93]
 [46  4]
 [55 35]
 [64 70]
 [27 11]
 [18 82]
 [91 40]]


In [68]:
points_in_space_groups

[array([[21, 30],
        [91, 51],
        [28, 39]]),
 array([[55, 35],
        [64, 70],
        [27, 11],
        [18, 82],
        [91, 40],
        [ 0, 40]])]

In [57]:
stack_points = np.vstack(points_in_space_groups).tolist()
stack_points

[[21, 30],
 [91, 51],
 [28, 39],
 [55, 35],
 [64, 70],
 [27, 11],
 [18, 82],
 [91, 40],
 [0, 40]]

In [ ]:
lat_tg = np.split(latitudes, indices)
lon_tg = np.split(longitudes, indices)

[array([30, 51, 39]), array([93,  4]), array([35, 70, 11, 82, 40, 40])]

In [67]:
lat_sg = [tg for tg, i in zip(lat_tg, labels) if i == 0]
lat_sg

[array([30, 51, 39]), array([35, 70, 11, 82, 40, 40])]

In [71]:
stack_lats = np.hstack(lat_sg).tolist()
stack_lats

[30, 51, 39, 35, 70, 11, 82, 40, 40]

traj_ids, speeds, edges, distances

---

---

In [190]:
import ast
datetimes = pd.to_datetime(df['timestamp'], errors='coerce') 
timestamps = datetimes.to_list()

In [191]:
arr = np.zeros(shape=(len(df), 4))

In [192]:
coords = np.array(df[['latitude', 'longitude']])
lat = df['latitude'].to_list()
lon = df['longitude'].to_list()

In [193]:
from datetime import timedelta
time_group_idx = []
time_diff = []
dist_diff = []
s = 0
max_time_diff = pd.Timedelta(minutes=2)
traj_ids = df['traj_id'].to_list()
num_points = len(df)

prev_id = traj_ids[0]
for i in range(1, num_points):
    cur_id = traj_ids[i-1]
    group_time_diff = timestamps[i] - timestamps[s]
    if cur_id == prev_id:
        time_diff.append((timestamps[i] - timestamps[i - 1]).total_seconds())
        dist_diff.append(round(np.linalg.norm(np.array([lon[i], lat[i]], dtype=np.float32) - np.array([lon[i - 1], lat[i - 1]], dtype=np.float32)), 2))
    if (group_time_diff > max_time_diff) or (cur_id != prev_id):
        time_group_idx.append((s, i))
        s = i
        prev_id = cur_id
time_group_idx.append((s, num_points + 1))
time_group_idx

[(0, 3), (3, 5), (5, 10), (10, 12)]

In [194]:
speed = [d/t for d, t in zip(dist_diff,time_diff)]
speed.append(speed[-1])
speed

[np.float32(0.81200004),
 np.float32(2.1376665),
 np.float32(0.781),
 np.float32(3.1003335),
 np.float32(0.15371428),
 np.float32(1.2046666),
 np.float32(2.3213334),
 np.float32(2.3856666),
 np.float32(2.8073335),
 np.float32(3.0333333),
 np.float32(3.0333333)]

In [195]:
indices = [end for _, end in time_group_idx[:-1]]     
grouped_lon = np.split(lon, indices)
two_lons = np.matrix([[l[0], l[-1]] for l in grouped_lon])
sorted_lons = np.asarray(np.sort(two_lons, axis=1))
grouped_lats = np.split(lat, indices)
two_lats = np.matrix([[l[0], l[-1]] for l in grouped_lats])
sorted_lats = (np.asarray(np.sort(two_lats, axis=1)))
print(sorted_lats)
print('--')
print(sorted_lons)

[[30 39]
 [ 4 93]
 [35 40]
 [40 40]]
--
[[21 28]
 [46 73]
 [55 91]
 [ 0  0]]


In [196]:
indices

[3, 5, 10]

In [197]:
mbrs = np.hstack((sorted_lats, sorted_lons))
mbrs

array([[30, 39, 21, 28],
       [ 4, 93, 46, 73],
       [35, 40, 55, 91],
       [40, 40,  0,  0]])

In [198]:
centroids = [( (x1+x2)/2, (y1+y2)/2 ) for x1, x2, y1, y2 in mbrs]

In [199]:
centroids

[(np.float64(34.5), np.float64(24.5)),
 (np.float64(48.5), np.float64(59.5)),
 (np.float64(37.5), np.float64(73.0)),
 (np.float64(40.0), np.float64(0.0))]

In [200]:
from shapely.geometry import box
from sklearn.cluster import KMeans
K = 2
# Cluster centroids
kmeans = KMeans(n_clusters=K).fit(centroids)
labels = kmeans.labels_

In [201]:
labels

array([1, 0, 0, 1], dtype=int32)

In [202]:
def get_bbox(lat, lon, labels, i):
    """
    Return [min_long, min_lat, max_long, max_lat] == [left, bottom, right, top]
    """
    g_lat = np.matrix([row for row, l in zip(lat, labels) if l == i])
    g_lon = np.matrix([row for row, l in zip(lon, labels) if l == i])
    
    return [np.min(g_lon), np.min(g_lat), np.max(g_lon), np.max(g_lat)]


space_groups = []
for i in range(K):
    space_groups.append(get_bbox(lat=sorted_lats, lon=sorted_lons, labels=labels, i=i))
space_groups

[[np.int64(46), np.int64(4), np.int64(91), np.int64(93)],
 [np.int64(0), np.int64(30), np.int64(28), np.int64(40)]]

In [203]:
ti_by_si = [row for row, l in zip(time_group_idx, labels) if l == 0]
ti_by_si_rewrite = [i for start, end in ti_by_si for i in range(start, end + 1)]
ti_by_si_rewrite

[3, 4, 5, 5, 6, 7, 8, 9, 10]

In [204]:
df_array = np.stack([lon, lat, speed]).transpose()
df_array

array([[21.        , 30.        ,  0.81200004],
       [91.        , 51.        ,  2.13766646],
       [28.        , 39.        ,  0.78100002],
       [73.        , 93.        ,  3.10033345],
       [46.        ,  4.        ,  0.15371428],
       [55.        , 35.        ,  1.20466661],
       [64.        , 70.        ,  2.32133341],
       [27.        , 11.        ,  2.38566661],
       [18.        , 82.        ,  2.80733347],
       [91.        , 40.        ,  3.0333333 ],
       [ 0.        , 40.        ,  3.0333333 ]])

In [205]:
df_array[0]

array([21.        , 30.        ,  0.81200004])

In [208]:
df_subset = [df_array[i] for i in ti_by_si_rewrite]
df_subset

[array([73.        , 93.        ,  3.10033345]),
 array([46.        ,  4.        ,  0.15371428]),
 array([55.        , 35.        ,  1.20466661]),
 array([55.        , 35.        ,  1.20466661]),
 array([64.        , 70.        ,  2.32133341]),
 array([27.        , 11.        ,  2.38566661]),
 array([18.        , 82.        ,  2.80733347]),
 array([91.       , 40.       ,  3.0333333]),
 array([ 0.       , 40.       ,  3.0333333])]

In [132]:
df_idx = [row for row, l in zip(df, labels) if l == 0]
df_idx

['traj_id', 'longitude']

In [ ]:
time_idx_subgroup = [row for row, l in zip(time_group_idx, ti_by_si) if l == i]
idx_slice = [i for start, end in time_idx_subgroup for i in range(start, end + 1)]
df_subset = [df[j] for j in idx_slice]

---

In [57]:
centroids = [(0.5, 0.5),
 (1.5, 1.5),
 (2, 4.5),
 (3, 9),
 (7.5, 1.5),
 (8, 4),
 (9, 6),
 (11, 1.5),
 (11, 3),
 (11,6.5)]

In [58]:
K = 2
# Cluster centroids
kmeans = KMeans(n_clusters=K).fit(centroids)
labels = kmeans.labels_

In [59]:
labels

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1], dtype=int32)

In [78]:
ex_mbrs = [[0,0,1,1],
           [0,0,2,2],
           [1,3,3,6],
           [2,8,4,10],
           [6,1,9,2],
           [7,2,9,6],
           [6,5,12,7],
           [9,0,13,3],
           [10,2,12,4],
           [10,5,12,8]]
sorted_lats = [[0,0],
               [0,0],
               [1,3],
               [2,8],
               [6,1],
               [7,2],
               [6,5],
               [9,0],
               [10,2],
               [10,5]]
sorted_lons = [[1,1],
               [2,2],
               [3,6],
               [4,10],
               [9,2],
               [9,6],
               [12,7],
               [13,3],
               [12,4],
               [12,8]]
stacked=np.hstack((sorted_lats, sorted_lons))
stacked

array([[ 0,  0,  1,  1],
       [ 0,  0,  2,  2],
       [ 1,  3,  3,  6],
       [ 2,  8,  4, 10],
       [ 6,  1,  9,  2],
       [ 7,  2,  9,  6],
       [ 6,  5, 12,  7],
       [ 9,  0, 13,  3],
       [10,  2, 12,  4],
       [10,  5, 12,  8]])

In [90]:
group1_lats = np.matrix([row for row, l in zip(sorted_lats, labels) if l == 1])
group0_lats = [row for row, l in zip(sorted_lats, labels) if l == 0]